[package]
name = "tuxmath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.1" }
bevy_egui = "0.20.3"
rand = "0.8.5"
serde = "1.0.163"
toml = "0.7.4"
