[[questions]]
text = "1+1=?"
actual = "2"

[[questions]]
text = "1+2=?"
actual = "3"

[[questions]]
text = "1+3=?"
actual = "4"

[[questions]]
text = "1+4=?"
actual = "5"
[[questions]]
text = "1+5=?"
actual = "6"
[[questions]]
text = "1+6=?"
actual = "7"
[[questions]]
text = "1+7=?"
actual = "8"
